# Generated by Django 3.1.1 on 2020-11-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discountprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
