# Generated by Django 3.1.1 on 2020-11-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discountprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discountprice',
            new_name='discount_price',
        ),
    ]
