# Generated by Django 3.1.1 on 2020-11-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201119_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Description',
            field=models.TextField(default='Descripcion basica del objeto'),
            preserve_default=False,
        ),
    ]
