# Generated by Django 3.1.1 on 2020-11-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
